SolarBeamApp/SLP15/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^new_usr/$', views.new_usr, name='new_usr'),
    url(r'^alta_usr/$', views.alta_usr, name='alta_usr'),
    url(r'^simulador/$', views.simulador, name='simulador'),
    url(r'^simulador/alta_cen/$', views.alta_cen, name='alta_cen'),
#    url(r'^simulador/oferta/$', views.oferta, name='oferta'),
    url(r'^getNode/$', views.getNode, name="getNode"),


]

SolarBeamApp/SolarBeamApp/urls.py
"""
Definition of urls for SolarBeamDemo.
"""

from datetime import datetime
from django.conf.urls import include, url
from app.forms import BootstrapAuthenticationForm
from app.views import *
from django.contrib.auth.views import login, logout
from django.contrib import admin
from SLP15.views import *

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^contact$', contact, name='contact'),
    url(r'^about', about, name='about'),
    url(r'^solver$', solver, name='solver'),
    url(r'^login$',
        login,
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        logout,
        {
            'next_page': '/',
        },
        name='logout'),
#    url(r'^reset/$', views.reset, name="password_reset"),
    url(r'^modelo1/', include('modelo1.urls')),
    url(r'^slp2015/', include('SLP15.urls')),
    url(r'^slp2017/', include('SLP17.urls')),
    url(r'^tarifas/', include('tarifas.urls')),
    url(r'^Solarbeam1.0/', include('Ciudades.urls')),
    url(r'^docs/', include('documentos.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^/slp2015/getNode/$', getNode, name="getNode")
    url('^', include('django.contrib.auth.urls')),
]

SolarBeamApp/tarifas/urls.py
from django.conf.urls import url

from . import views
app_name = 'tarifas'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tarifa1/$', views.tarifa1, name='tarifa1'),
    url(r'^dac/$', views.dac, name='dac'),
    url(r'^tarifa1/(?P<ciudades_id>[0-9]+)/$', views.detalles, name='detalles'),
    url(r'^tarifa2/$', views.tarifa2, name='tarifa2'),
    url(r'^tarifa2/energia/$', views.t2energia, name='t2energia'),
    url(r'^dac/(?P<areascontrol_id>[0-9]+)/$', views.dac2, name='dac2'),
]

SolarBeamApp/tarifas/models.py
from __future__ import unicode_literals

from django.db import models

class Temporada(models.Model):
    Temporada = models.CharField(max_length=50)
    def __str__(self):
        return self.Temporada
class AreasControl(models.Model):
    AreasControl = models.CharField(max_length=50)
    def __str__(self):
        return self.AreasControl

class Estados(models.Model):
    Estados = models.CharField(max_length=50)
    def __str__(self):
        return self.Estados

class Anio(models.Model):
    Anio = models.IntegerField(default = 2000)
    def __str__(self):
        return str(self.Anio)

class Meses(models.Model):
    Meses = models.CharField(max_length=50)
    Dias = models.IntegerField(default = 30)
    def __str__(self):
        return self.Meses

class Tarifa1x(models.Model):
    Nombre = models.CharField(max_length=200)
    Temp = models.ForeignKey(Temporada)
    Basico = models.FloatField(default = 0)
    Inter_Bajo = models.FloatField(default = 0)
    Inter_Medio = models.FloatField(default = 0)
    Excedente = models.FloatField(default = 0)
    CBasico = models.FloatField(default = 0)
    CInter_Bajo = models.FloatField(default = 0)
    CInter_Medio = models.FloatField(default = 0)
    CExcedente = models.FloatField(default = 0)
    DAC = models.IntegerField(default = 0)
    Anio = models.ForeignKey(Anio, blank=True, null=True)
    def __str__(self):
        return self.Nombre

class Tarifa2(models.Model):
    Mes = models.ForeignKey(Meses, blank=True, null=True)
    Anio = models.ForeignKey(Anio, blank=True, null=True)
    Basico = models.FloatField(default = 0)
    Inter = models.FloatField(default = 0)
    Excedente = models.FloatField(default = 0)
    CBasico = models.FloatField(default = 50)
    CInter = models.FloatField(default = 50)
    Cargofijo = models.FloatField(default = 60)
    def __unicode__(self):
        return '%s %s' % ((str(self.Mes)), str(self.Anio))

class Ciudades(models.Model):
    Nombre = models.CharField(max_length=200)
    Estado = models.ForeignKey(Estados)
    AreaCont = models.ForeignKey(AreasControl)
    Tarifa = models.CharField(max_length=200, blank=True, null=True)
    Verano = models.ForeignKey(Meses, blank=True, null=True)
    def __str__(self):
        return self.Nombre

class DAC(models.Model):
    Fijo = models.FloatField(default = 0)
    AreaCont = models.ForeignKey(AreasControl)
    Costo_kWh_verano= models.FloatField(default = 0)
    Costo_kWh_fverano= models.FloatField(default = 0)
    Anio = models.ForeignKey(Anio, blank=True, null=True)
    Mes = models.ForeignKey(Meses, blank=True, null=True)
    def __unicode__(self):
        return '%s %s %s' % (str(self.AreaCont), str(self.Mes), str(self.Anio))

SolarBeamApp/tarifas/views.py
from django.shortcuts import get_object_or_404, render
from .models import Ciudades, DAC, Tarifa1x, Meses, Tarifa2, Anio, AreasControl
from datetime import datetime
import graf, tarf2ener, grafd

def index(request):
    context = {'year':datetime.now().year}
    return render(request, 'tarifas/index.html', context)

def tarifa1(request):
    ciudades = Ciudades.objects.all()
    context = {'ciudades':ciudades, 'year':datetime.now().year}
    return render(request, 'tarifas/tarifa1.html', context)

def detalles(request, ciudades_id):
    ciudad = get_object_or_404(Ciudades, pk=ciudades_id)
    tarifa = Tarifa1x.objects.filter(Nombre__startswith = ciudad.Tarifa+" -")
    context = {'ciudad':ciudad, 'tarifa':tarifa, 'year':datetime.now().year}
    return render(request, 'tarifas/detalles.html', context)

def tarifa2(request):
    tarifa2_historico = Tarifa2.objects.order_by('-Anio', 'Mes')
    mes = Meses.objects.all()
    anio = Anio.objects.all()
    graf.main(tarifa2_historico)
    context = {'year':datetime.now().year, 'hist':tarifa2_historico, 'meses': mes, 'anio': anio}
    return render(request, 'tarifas/tarifa2.html', context)

def t2energia(request):
    init = int(request.POST['init'])
    ulti = int(request.POST['ulti'])
    fact = float(request.POST['fact'])
    mes1 = get_object_or_404(Meses, pk=request.POST['mes1'])
    mes2 = get_object_or_404(Meses, pk=request.POST['mes2'])
    a = int(request.POST['mes1'])
    b = int(request.POST['mes2'])
    c = b - a
    if c > 1:
        mes3 =get_object_or_404(Meses, pk = a + 1)
        fact3 = Tarifa2.objects.filter(Anio = request.POST['anio'], Mes=mes3)
    else:
        mes3 = 0
        fact3 = 0
    fact1 = Tarifa2.objects.filter(Anio = request.POST['anio'], Mes=mes1)
    fact2 = Tarifa2.objects.filter(Anio = request.POST['anio'], Mes=mes2)
    cost, iva, total = tarf2ener.main(init, ulti, fact, mes1, mes2, fact1, fact2, mes3, fact3)
    context = {'cost': cost, 'iva': iva, 'total': total}
    return render(request, 'tarifas/t2energia.html', context)

def dac(request):
    Acont = AreasControl.objects.all()
    context = {'Acont': Acont}
    return render(request, 'tarifas/dac.html', context)

def dac2(request, areascontrol_id):
    acont = get_object_or_404(AreasControl, pk=areascontrol_id)
    dac = DAC.objects.filter(AreaCont= acont).order_by('-Anio', 'Mes')
    grafd.main(dac, acont)
    context = {'dac': dac, 'acont': acont}
    return render(request, 'tarifas/dac2.html', context)

SolarBeamApp/tarifas/templates/tarifas/dac.html
{% extends "app/layout.html" %}
{% block title %}Tarifas de Alto Consumo residencial{% endblock %}
{% load static %}
{% block content %}
<h1 align = "center">Tarifas de Alto Consumo residencial</h1>
{% for i in Acont %}
<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="{% url 'tarifas:dac2' i.id %}" method="post" >
    {% csrf_token %}
    <div class="row form-group">
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="{{ i.AreasControl }}" id="btnSend" />
        </div>
    </div>
</form>
{% endfor %}
{% endblock %}

SolarBeamApp/tarifas/templates/tarifas/dac2.html
{% extends "app/layout.html" %}
{% block title %}Tarifas de Alto Consumo residencial{% endblock %}
{% load static %}
{% block content %}
<h1 align = "center">Tarifas de Alto Consumo {{acont}}</h1>
<div class="row form-group" align = "center">
<img src="{% static 'tarifas/tarifadac_' %}{{acont}}.png" alt="Grafica"/>
</div>

<div class="row form-group" align = "center">
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Año</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Mes</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Cargo fijo</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Tarifa de Verano</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Tarifa fuera de Verano</span>
    </div>

{% for i in dac %}
    {% csrf_token %}
    <div class="row form-group" align = "center">
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Anio}}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Mes }}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Fijo }}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Costo_kWh_verano}}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Costo_kWh_fverano }}</span>
            
    </div>

{% endfor %}
{% endblock %}

SolarBeamApp/tarifas/templates/tarifas/detalles.html
{% extends "app/layout.html" %}
{% block title %}Tarifas Residenciales CFE{% endblock %}
{% block content %}
<h1>Ciudades</h1>
    {% csrf_token %}
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">1.- Ciudad</span>
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ ciudad.Nombre }}</span>
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">2.- Tarifa</span>
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ ciudad.Tarifa }}</span>
    </div>
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">3.- Mes de inicio de verano</span>
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ ciudad.Verano }}</span>
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">4.- Area de Control</span>
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ ciudad.AreaCont }}</span>
    </div>
    {% for i in tarifa %}
        <div class="row form-group">
            <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">5.- Nombre</span>
            <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.Nombre }}</span>
            <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">6.- Precio Basico</span>
            <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.Basico }}</span>
        </div>
        <div class="row form-group">
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">7.- Precio Intermedio bajo</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.Inter_Bajo }}</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">8.- Precio Intermedio Alto</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.Inter_Medio }}</span>
        </div>
        <div class="row form-group">
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">9.- Precio Excedente</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.Excedente }}</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">10.- Maximo consumo Basico</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.CBasico }}</span>
        </div>
        <div class="row form-group">
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">11.- Maximo consumo Intermedio Bajo</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.Excedente }}</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">12.- Maximo consumo Intermedio Alto</span>
             <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">{{ i.CBasico }}</span>
        </div>
    {% endfor %}
{% endblock %}

SolarBeamApp/tarifas/templates/tarifas/index.html
{% extends "app/layout.html" %}
{% block title %}Tarifas Residenciales CFE{% endblock %}
{% block content %}
<h1>Ciudades</h1>
<div class="row form-group">
<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="{% url 'tarifas:tarifa1' %}" method="post" >
    {% csrf_token %}  
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="Residencial" id="btnSend" />
        </div>
</form>
    <form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="{% url 'tarifas:dac' %}" method="post" >
    {% csrf_token %}
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="De Alto Consumo" id="btnSend" />
        </div>
   </form>
    </div>



<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="{% url 'tarifas:tarifa2' %}" method="post" >
    {% csrf_token %}
    <div class="row form-group">
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="Comercial" id="btnSend" />
        </div>
    </div>
</form>
{% endblock %}

SolarBeamApp/tarifas/templates/tarifas/t2energia.html
{% extends "app/layout.html" %}
{% block title %}Tarifas Comerciales CFE{% endblock %}
{% block content %}
{% load static %}

<h1 align = "center">Pago</h1>



<div class="row form-group" align = "center">
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">Costo</span>
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">Iva</span>
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">Total</span>
</div>
<div class="row form-group" align = "center">
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">{{ cost }}</span>
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">{{ iva }}</span>
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">{{ total }}</span>
</div>
<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="/tarifas/tarifa2/" method="post" >
    <div class="row form-group" align = "center">
           
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="submit" class="form-control btn-primary" value="Regresar" id="btnSend" />
            </div>
    </div>

{% endblock %}

SolarBeamApp/tarifas/templates/tarifas/tarifa1.html
{% extends "app/layout.html" %}
{% block title %}Tarifas Residenciales CFE{% endblock %}
{% block content %}
<h1>Ciudades</h1>
{% for i in ciudades %}
<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="{% url 'tarifas:detalles' i.id %}" method="post" >
    {% csrf_token %}
    <div class="row form-group">
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="{{ i.Nombre }}" id="btnSend" />
        </div>
    </div>
</form>
{% endfor %}
{% endblock %}

SolarBeamApp/tarifas/templates/tarifas/tarifa2.html
{% extends "app/layout.html" %}
{% block title %}Tarifas Comerciales CFE{% endblock %}
{% block content %}
{% load static %}

<h1 align = "center">Historial de Precios</h1>
<div class="row form-group" align = "center">
<img src="{% static "tarifas/tarifa2_hist.png" %}" alt="Grafica"/>
</div>


<div class="row form-group" align = "center">
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Anio</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Primer dia</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Mes</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Ultimo dia</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Mes</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Consumo kWh</span>
</div>
<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="energia/" method="post" >
    <div class="row form-group" align = "center">
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <select class="form-control" name="anio" id="anio">
                {% for i in anio %}
                    <option value="{{i.id}}">{{ i.get_anio_display}} {{ i.Anio }}</option>
                {% endfor %}
            </select>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="number" step="any" id="init" name="init" class="form-control" value="{{ init }}" min="1" required/>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <select class="form-control" name="mes1" id="mes1">
                {% for i in meses %}
                    <option value="{{i.id}}">{{ i.get_meses_display}} {{ i.Meses }}</option>
                {% endfor %}
            </select>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="number" step="any" id="ulti" name="ulti" class="form-control" value="{{ ulti }}" min="1" required/>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <select class="form-control" name="mes2" id="mes2">
                {% for i in meses %}
                    <option value="{{i.id}}">{{ i.get_meses_display}} {{ i.Meses }}</option>
                {% endfor %}
            </select>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="number" step="any" id="fact" name="fact" class="form-control" value="{{ fact }}" min="0" required/>
            </div>
    </div>
    <div class="row form-group" align = "center">  
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="submit" class="form-control btn-primary" value="Enviar" id="btnSend" />
            </div>
    </div>
<div class="row form-group" align = "center">
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Año</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Mes</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Cargo fijo</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Basico</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Intermedio</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">Excedente</span>
    </div>

{% for i in hist %}
    {% csrf_token %}
    <div class="row form-group" align = "center">
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Anio}}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Mes }}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Cargofijo }}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Basico}}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Inter }}</span>
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">{{ i.Excedente }}</span>
            
    </div>

{% endfor %}
{% endblock %}