SolarBeamApp/SLP15/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^new_usr/$', views.new_usr, name='new_usr'),
    url(r'^alta_usr/$', views.alta_usr, name='alta_usr'),
    url(r'^simulador/$', views.simulador, name='simulador'),
    url(r'^simulador/alta_cen/$', views.alta_cen, name='alta_cen'),
#    url(r'^simulador/oferta/$', views.oferta, name='oferta'),
    url(r'^getNode/$', views.getNode, name="getNode"),


]

SolarBeamApp/SLP17/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^new_usr/$', views.new_usr, name='new_usr'),
    url(r'^alta_usr/$', views.alta_usr, name='alta_usr'),
    url(r'^simulador/$', views.simulador, name='simulador'),
    url(r'^simulador/alta_cen/$', views.alta_cen, name='alta_cen'),
    url(r'^simulador/alta_cen/alta/$', views.alta_cen2, name='alta_cen2'),
#    url(r'^simulador/oferta/$', views.oferta, name='oferta'),
    url(r'^getNode/$', views.getNode, name="getNode"),
    url(r'^simulador/alta_paq/$', views.alta_paq1, name='alta_paq1'),
    url(r'^simulador/alta_paq/paq/$', views.alta_paq2, name='alta_paq2'),


]

SolarBeamApp/SolarBeamApp/urls.py
"""
Definition of urls for SolarBeamDemo.
"""

from datetime import datetime
from django.conf.urls import include, url
from app.forms import BootstrapAuthenticationForm
from app.views import *
from django.contrib.auth.views import login, logout
from django.contrib import admin
from SLP15.views import *

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^contact$', contact, name='contact'),
    url(r'^about', about, name='about'),
    url(r'^solver$', solver, name='solver'),
    url(r'^login$',
        login,
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        logout,
        {
            'next_page': '/',
        },
        name='logout'),
#    url(r'^reset/$', views.reset, name="password_reset"),
    url(r'^modelo1/', include('modelo1.urls')),
    url(r'^slp2015/', include('SLP15.urls')),
    url(r'^slp2017/', include('SLP17.urls')),
    url(r'^tarifas/', include('tarifas.urls')),
    url(r'^Solarbeam1.0/', include('Ciudades.urls')),
    url(r'^docs/', include('documentos.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^/slp2015/getNode/$', getNode, name="getNode")
    url('^', include('django.contrib.auth.urls')),
]

SolarBeamApp/app/models.py
"""
Definition of models.
"""

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Anexo2Centrales(models.Model):
    nombre_cen = models.TextField(db_column='NOMBRE_CEN')  # Field name made lowercase.
    central = models.IntegerField(db_column='CENTRAL')  # Field name made lowercase.
    capapl = models.IntegerField(db_column='CAPAPL')  # Field name made lowercase.
    zpcen = models.IntegerField(db_column='ZPCEN')  # Field name made lowercase.
    zgcen = models.IntegerField(db_column='ZGCEN')  # Field name made lowercase.
    zprcen = models.IntegerField(db_column='ZPRCEN')  # Field name made lowercase.
    zicen = models.IntegerField(db_column='ZICEN')  # Field name made lowercase.
    gen = models.IntegerField(db_column='GEN')  # Field name made lowercase.
    prelacion = models.IntegerField(db_column='PRELACION')  # Field name made lowercase.
    cent_acept = models.IntegerField(db_column='CENT_ACEPT', blank=True, null=True)  # Field name made lowercase.
    factorp = models.DecimalField(db_column='FACTORP', max_digits=10, decimal_places=4)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ANEXO_2_CENTRALES'


class Anexo2CentralOv(models.Model):
    gen = models.IntegerField(db_column='GEN')  # Field name made lowercase.
    paquetes = models.IntegerField(db_column='PAQUETES')  # Field name made lowercase.
    central = models.IntegerField(db_column='CENTRAL')  # Field name made lowercase.
    porceea = models.DecimalField(db_column='PORCEEA', max_digits=10, decimal_places=4)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ANEXO_2_CENTRAL_OV'


class Anexo2Confzgen(models.Model):
    gen = models.IntegerField(db_column='GEN')  # Field name made lowercase.
    rinpre = models.IntegerField(db_column='RINPRE')  # Field name made lowercase.
    nodin = models.IntegerField(db_column='NODIN')  # Field name made lowercase.
    paquetes = models.IntegerField(db_column='PAQUETES')  # Field name made lowercase.
    sinterc = models.IntegerField(db_column='SINTERC')  # Field name made lowercase.
    zongen = models.IntegerField(db_column='ZONGEN')  # Field name made lowercase.
    zprecio = models.IntegerField(db_column='ZPRECIO')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ANEXO_2_CONFZGEN'


class Anexo2Factordesesp(models.Model):
    factorprefpesos = models.DecimalField(db_column='FACTORPREFPESOS', max_digits=10, decimal_places=8)  # Field name made lowercase.
    porciondlsnominal = models.DecimalField(db_column='PORCIONDLSNOMINAL', max_digits=10, decimal_places=8)  # Field name made lowercase.
    porciondlsreal = models.DecimalField(db_column='PORCIONDLSREAL', max_digits=10, decimal_places=8)  # Field name made lowercase.
    porcionpesosrealid = models.DecimalField(db_column='PORCIONPESOSREALID', max_digits=10, decimal_places=8)  # Field name made lowercase.
    tasadevesp = models.DecimalField(db_column='TASADEVESP', max_digits=10, decimal_places=8)  # Field name made lowercase.
    porcionpesosnominal = models.DecimalField(db_column='PORCIONPESOSNOMINAL', max_digits=10, decimal_places=8)  # Field name made lowercase.
    porcionpesosrealip = models.DecimalField(db_column='PORCIONPESOSREALIP', max_digits=10, decimal_places=8)  # Field name made lowercase.
    tasabonos = models.DecimalField(db_column='TASABONOS', max_digits=10, decimal_places=8)  # Field name made lowercase.
    tasabonosusd = models.DecimalField(db_column='TASABONOSUSD', max_digits=10, decimal_places=8)  # Field name made lowercase.
    tasaembi = models.DecimalField(db_column='TASAEMBI', max_digits=10, decimal_places=8)  # Field name made lowercase.
    tasaudibono = models.DecimalField(db_column='TASAUDIBONO', max_digits=10, decimal_places=8)  # Field name made lowercase.
    tasatips = models.DecimalField(db_column='TASATIPS', max_digits=10, decimal_places=8)  # Field name made lowercase.
    p = models.IntegerField(db_column='P')  # Field name made lowercase.
    e = models.IntegerField(db_column='E')  # Field name made lowercase.
    c = models.IntegerField(db_column='C')  # Field name made lowercase.
    i = models.DecimalField(db_column='I', max_digits=10, decimal_places=8)  # Field name made lowercase.
    iden = models.DecimalField(db_column='ID', max_digits=10, decimal_places=8)  # Field name made lowercase.
    t = models.DecimalField(db_column='T', max_digits=10, decimal_places=8)  # Field name made lowercase.
    umbral_sener = models.DecimalField(db_column='UMBRAL_SENER', max_digits=10, decimal_places=8)  # Field name made lowercase.
    tcusd = models.DecimalField(db_column='TCUSD', max_digits=10, decimal_places=8)  # Field name made lowercase.
    usd_compra = models.DecimalField(db_column='USD_COMPRA', max_digits=10, decimal_places=8)  # Field name made lowercase.
    vpnusda = models.DecimalField(db_column='VPNUSDA', max_digits=10, decimal_places=8)  # Field name made lowercase.
    vpnusdb = models.DecimalField(db_column='VPNUSDB', max_digits=10, decimal_places=8)  # Field name made lowercase.
    vpnmxna = models.DecimalField(db_column='VPNMXNA', max_digits=10, decimal_places=8)  # Field name made lowercase.
    vpnmxnb = models.DecimalField(db_column='VPNMXNB', max_digits=10, decimal_places=8)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ANEXO_2_FACTORDESESP'


class Anexo2Ofererc(models.Model):
    dpot = models.FloatField(db_column='DPOT', blank=True, null=True)  # Field name made lowercase.
    ppot = models.FloatField(db_column='PPOT', blank=True, null=True)  # Field name made lowercase.
    deea = models.IntegerField(db_column='DEEA', blank=True, null=True)  # Field name made lowercase.
    peea = models.IntegerField(db_column='PEEA', blank=True, null=True)  # Field name made lowercase.
    dcel = models.IntegerField(db_column='DCEL', blank=True, null=True)  # Field name made lowercase.
    pcel = models.IntegerField(db_column='PCEL', blank=True, null=True)  # Field name made lowercase.
    fechairrantp = models.IntegerField(db_column='FECHAIRRANTP', blank=True, null=True)  # Field name made lowercase.
    fechairrdespp = models.IntegerField(db_column='FECHAIRRDESPP', blank=True, null=True)  # Field name made lowercase.
    fechairrante = models.IntegerField(db_column='FECHAIRRANTE', blank=True, null=True)  # Field name made lowercase.
    fechairrdespe = models.IntegerField(db_column='FECHAIRRDESPE', blank=True, null=True)  # Field name made lowercase.
    fechairrantc = models.IntegerField(db_column='FECHAIRRANTC', blank=True, null=True)  # Field name made lowercase.
    fechairrdespc = models.IntegerField(db_column='FECHAIRRDESPC', blank=True, null=True)  # Field name made lowercase.
    erc = models.IntegerField(db_column='ERC', blank=True, null=True)  # Field name made lowercase.
    ofertas = models.IntegerField(db_column='OFERTAS', blank=True, null=True)  # Field name made lowercase.
    zpoterc = models.IntegerField(db_column='ZPOTERC', blank=True, null=True)  # Field name made lowercase.
    sinterc = models.IntegerField(db_column='SINTERC', blank=True, null=True)  # Field name made lowercase.
    rinerc = models.IntegerField(db_column='RINERC', blank=True, null=True)  # Field name made lowercase.
    potajus = models.IntegerField(db_column='POTAJUS', blank=True, null=True)  # Field name made lowercase.
    eeaajus = models.IntegerField(db_column='EEAAJUS', blank=True, null=True)  # Field name made lowercase.
    celajus = models.IntegerField(db_column='CELAJUS', blank=True, null=True)  # Field name made lowercase.
    ejecucion = models.TextField(db_column='EJECUCION', blank=True, null=True)  # Field name made lowercase.
    ppotajus = models.FloatField(db_column='PPOTAJUS', blank=True, null=True)  # Field name made lowercase.
    peeaajus = models.IntegerField(db_column='PEEAAJUS', blank=True, null=True)  # Field name made lowercase.
    pcelajus = models.IntegerField(db_column='PCELAJUS', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ANEXO_2_OFERERC'


class Anexo2Paqexc(models.Model):
    gen = models.IntegerField(db_column='GEN', blank=True, null=True)  # Field name made lowercase.
    conpaqexc = models.IntegerField(db_column='CONPAQEXC', blank=True, null=True)  # Field name made lowercase.
    paquetes = models.IntegerField(db_column='PAQUETES', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ANEXO_2_PAQEXC'


class Anexo2Paqin(models.Model):
    gen = models.IntegerField(db_column='GEN', blank=True, null=True)  # Field name made lowercase.
    paquetes = models.IntegerField(db_column='PAQUETES', blank=True, null=True)  # Field name made lowercase.
    paquetes2 = models.IntegerField(db_column='PAQUETES2', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ANEXO_2_PAQIN'


class Anexo2Regionof(models.Model):
    sistemainter = models.IntegerField(db_column='SISTEMAINTER', blank=True, null=True)  # Field name made lowercase.
    zona = models.IntegerField(db_column='ZONA', blank=True, null=True)  # Field name made lowercase.
    region = models.IntegerField(db_column='REGION', blank=True, null=True)  # Field name made lowercase.
    nombrereg = models.TextField(db_column='NOMBREREG', blank=True, null=True)  # Field name made lowercase.

SolarBeamApp/SLP17/templates/SLP17/alta_cen.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% load staticfiles %}
{% block content %}
<h1>Simulador</h1>

<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="alta/" method="post" >
    {% csrf_token %}
    <div class="row form-group">
        <span class="col-md-5 col-sm-5 col-xs-5 col-lg-5">1.- Quiero generar con una central con Capacidad de</span>
        <div class="col-md-2">
            <input type="number" step="any" id="capapl" name="capapl" class="form-control" value="{{ capapl }}" min="0" required/>
        </div>
        <span class="col-md-1 col-sm-1 col-lg-1 col-xs-1"> MW</span>
    </div>
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">2.- Regi&oacute;n de transmisi&oacute;n:</span>
        <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3">
            <select class="form-control" name="region" id="region">
                <option value="0">Selecciona una opci&oacute;n</option>
                {% for i in regionof %}
                    <option value="{{i.id}}">{{ i.get_nombrereg_display}} {{ i.nombrereg }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">3.- Punto de interconexi&oacute;n:</span>
        <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3">
            <select class="form-control" name="nodo" id="nodo" disabled>
                <option value="0">Selecciona una opci&oacute;n</option>
            </select>
        </div>
    </div>
    <div class="row form-group">
        <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4"> 4.- Mi central cuenta con prelaci&oacute;n:</span>
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <select class="form-control" name="prelacion" id="cenPre"> 
                <option value="0">Si</option>
                <option value="1">No</option>
            </select>
        </div>
    </div>
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">5.- El nombre de mi central es:</span>
        <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4">
            <input type="text" class="form-control" step="any" name="nombre_cen" id="nameCen" value="{{ nombre_cen }}" required/>
        </div>
    </div>
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">6.- La tecnología de mi central es:</span>
        <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4">
            <input type="text" class="form-control" step="any" name="tec_cen" id="tecCen" value="{{ tec_cen }}" required/>
        </div>
    </div>
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">7.- El factor de planta de mi central es:</span>
        <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4">
            <input type="text" class="form-control" step="any" name="fact_cen" id="factCen" value="{{ fact_cen }}" required/>
        </div>
    </div>
    <div class="row form-group">
        <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3">8.- El porcentaje de energía limpia de mi central es:</span>
        <div class="col-md-4 col-sm-4 col-xs-4 col-lg-4">
            <input type="text" class="form-control" step="any" name="limp_cen" id="limpCen" value="{{ limp_cen }}" required/>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="Enviar" id="btnSend" />
        </div>
    </div>
</form>
<script src="{% static 'SLP2015/simulador.js' %}"></script>
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/alta_cen2.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% load staticfiles %}
{% block content %}
<h1>Central dada de alta</h1>

 <div class="row form-group">
        <div class="col-md-2">
            <a href="{% url 'alta_cen' %}"><input type="submit" value="Alta de central" class="btn btn-default"/></a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'alta_paq1' %}"><input type="submit" value="Alta de Oferta" class="btn btn-default"/></a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'password_reset' %}"><input type="submit" value="Ofertas condicionadas" class="btn btn-default"/></a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'password_reset' %}"><input type="submit" value="Ofertas excluyentes" class="btn btn-default"/></a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'simulador' %}"><input type="submit" value="Ofertas excluyentes" class="btn btn-default"/></a>
        </div>
    </div>
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/alta_paq1.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% load staticfiles %}
{% block content %}
<h3>Elija la(s) central(es) asociada a la Oferta de Venta</h3>

<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="{% url 'alta_paq2' %}" method="post" >
    {% csrf_token %}
    <div class="row form-group">
        <table> 
         <tr>
            <td></td> <td>   Número de Central   </td><td>    Nombre de la central </td><td> Capacidad de la Central en MW    </td>
         </tr>
            {% for i in cent %}
            <tr>       
                <td> <input type="checkbox" name= "checks[]" value= "{{ i.id }}"></td><td> {{i.central}} </td><td> {{i.nombre_cen}} </td><td> {{i.capapl}} </td>
            </tr>
            {% endfor %}
         </table>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="Enviar" id="btnSend" />
        </div>
    </div>
</form>
<script src="{% static 'SLP2015/simulador.js' %}"></script>
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/alta_usr.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% load staticfiles %}
{% block content %}
<h1>Simulador</h1>

<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="/slp2015/alta_usr" method="post" >
    {% csrf_token %}
    <div class="row form-group">
        <span class="col-md-5 col-sm-5 col-xs-5 col-lg-5">Usuario creado correctamente {{user.id}}</span>
        
    </div>
</form>
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/index.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% block content %}
<h1 align = center>Subasta de Largo Plazo 2015</h1>
 <div class="row form-group">
        Subasta sin modificaciones <br>
    <form name = 'entr' onsubmit="return validateForm()" action="resultados/" method="post" >
        {% csrf_token %}
    <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2"><input type="submit" class="form-control btn-primary" value="Enviar" id="btn_s" /></div>
        </form>
 </div>
 <br>
 <div class="row form-group">
    Simulador <br>
    <form name = 'entra' onsubmit="return validateForm()" action="simulador/" method="post" >
        {% csrf_token %}
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2"><input type="submit" class="form-control btn-primary" value="Enviar" id="btn_s" /></div>
        </form>
 </div>
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/new_usr.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% load staticfiles %}
{% block content %}
<h1>Simulador</h1>

<form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="/slp2015/alta_usr/" method="post" >
    {% csrf_token %}
    <div class="row form-group">
        <span class="col-md-5 col-sm-5 col-xs-5 col-lg-5">1.- Correo electrónico</span>
        <div class="col-md-2">
            <input type="text" step="any" id="email" name="email" class="form-control" value="{{ email }}" required/>
        </div>
    </div>
    <div class="row form-group">
        <span class="col-md-5 col-sm-5 col-xs-5 col-lg-5">2.- Password</span>
        <div class="col-md-2">
            <input type="password" step="any" id="password" name="password" class="form-control" value="{{ password }}" required/>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="Enviar" id="btnSend" />
        </div>
    </div>
</form>
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/oferta.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% block content %}

    Simulador
    <form name = 'entra' onsubmit="return validateForm()" action="resultados/" method="post" >
        {% csrf_token %}
        
        1.-Quiero ofertar <input type="number" step="any" name="gpot" style="width: 6em" value="{{ gpot }}" required/> MW de Potencia, 
             <input type="number" step="any" name="geea" style="width: 6em" value="{{ geea }}" required/> MWh de Energia Electrica acumulable y  
             <input type="number" step="any" name="gcel" style="width: 6em" value="{{ gcel }}" required/> Certificados de energia limpia a un precio anual de 
             <input type="number" step="any" name="ppaq" style="width: 6em" value="{{ ppaq }}" required/> pesos.
        <br><br>
        2.- Los productos se entergarán en: &nbsp;<select name="fecha"> 
                <option value="0">Fecha estandar</option>
                <option value="1">Fecha irregular anterior</option>
                <option value="2">Fecha irregular posterior</option>
                </select><br><br>
         3.- El pago será en: &nbsp;<select name="indexusd"> 
                <option value="0">Pesos</option>
                <option value="1">Dolares</option>
                </select><br><br>
         
        <div class="centrar"><input type="submit" value="Enviar" id="btn_s" /></div>
        </form>
    </p>
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/resultados.html
{% extends "app/layout.html" %}
{% block content %}
{% if slp2015 %}
<p>
    <table align ="center">
        <tr><td>{{ status }}</td></tr>
        <tr><td> Resultado Simulacion funcion objetivo </td><td> {{ fob }} </td><td> Resultado Cenace funcion objetivo </td><td> 2459051813 </td></tr>
        <tr><td># Paquete </td><td> Resultado simulacion </td><td> Resultado CENACE </td><td> Licitante </td><td> Oferta </td><td> Potencia ofertada </td><td> Energia ofertada </td><td> Cels Ofertados </td><td> Precio ofertado </td>
        {% for j in Up %}  
               
            <tr> 
                {% for i in j %}
                   <td>{{ i }}  </td>
                 {% endfor %}
            </tr>
        
        {% endfor %}
        
    </table>
    <br><br>
    <table align ="center">
        <tr><td># OFerta </td><td> Comprador </td><td> Oferta </td><td> Compra de Potencia </td><td> Oferta potencia </td><td> Compra energia </td><td> Oferta energia </td><td> Compra Cel </td><td> Oferta Cel </td>
        {% for j in Compra %}  
               <tr>
                   {% for i in j %}
                       <td>{{ i }}  </td>
                   {% endfor %}
              </tr>
              
        {% endfor %} 
        
    </table>
</p>
{% else %}
    <p>No hay comida</p>
{% endif %}
{% endblock %}

SolarBeamApp/SLP17/templates/SLP17/simulador.html
{% extends "app/layout.html" %}
{% block title %}Primera Subasta de Largo Plazo SLP2015{% endblock %}
{% load staticfiles %}
{% block content %}
<h1>Simulador</h1>

    {% csrf_token %}
    <div class="row form-group">
        <div class="col-md-2">
            <a href="{% url 'alta_cen' %}"><input type="submit" value="Alta de central" class="btn btn-default"/></a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'alta_paq1' %}"><input type="submit" value="Alta de Oferta" class="btn btn-default"/></a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'password_reset' %}"><input type="submit" value="Ofertas condicionadas" class="btn btn-default"/></a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'password_reset' %}"><input type="submit" value="Ofertas excluyentes" class="btn btn-default"/></a>
        </div>
    </div>
    {% if cent %}
         <h3>Centrales dadas de alta</h3>
         <table> 
         <tr>
             <td>   Número de Central   </td><td>    Nombre de la central </td><td> Capacidad de la Central en MW    </td>
         </tr>
            {% for i in cent %}
            <tr>
                 {% for j in i %}
                 <td>{{ j }}  </td>
             {% endfor %}
            </tr>
            {% endfor %}
         </table>
    {% else %}
        <h3>No hay Centrales dadas de alta</h3>
    {% endif %}
    {% if paq %}
        <h3>Ofertas de venta dadas de alta</h3>
        <tr>
             {% for i in paq %}
                 <td>{{ i }}  </td>
             {% endfor %}
         </tr>
    {% else %}
        <h3>No hay Ofertas de venta dadas de alta</h3>
    {% endif %}

{% endblock %}