SolarBeamApp/Ciudades/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^Solarbeam2/$', views.Solarbeam2, name='Solarbeam2'),
    url(r'^Solarbeam2/resumen/$', views.resumen, name='resumen'),
    url(r'^reporte/$', views.resultados, name='resultados'),
]

SolarBeamApp/SLP15/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^resultados/$', views.resultados, name='resultados'),
    url(r'^new_usr/$', views.new_usr, name='new_usr'),
    url(r'^alta_usr/$', views.alta_usr, name='alta_usr'),
    url(r'^simulador/$', views.simulador, name='simulador'),
    url(r'^simulador/alta_cen/$', views.alta_cen, name='alta_cen'),
#    url(r'^simulador/oferta/$', views.oferta, name='oferta'),
    url(r'^getNode/$', views.getNode, name="getNode"),


]

SolarBeamApp/SolarBeamApp/urls.py
"""
Definition of urls for SolarBeamDemo.
"""

from datetime import datetime
from django.conf.urls import include, url
from app.forms import BootstrapAuthenticationForm
from app.views import *
from django.contrib.auth.views import login, logout
from django.contrib import admin
from SLP15.views import *

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^contact$', contact, name='contact'),
    url(r'^about', about, name='about'),
    url(r'^solver$', solver, name='solver'),
    url(r'^login$',
        login,
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        logout,
        {
            'next_page': '/',
        },
        name='logout'),
#    url(r'^reset/$', views.reset, name="password_reset"),
    url(r'^modelo1/', include('modelo1.urls')),
    url(r'^slp2015/', include('SLP15.urls')),
    url(r'^slp2017/', include('SLP17.urls')),
    url(r'^tarifas/', include('tarifas.urls')),
    url(r'^Solarbeam1.0/', include('Ciudades.urls')),
    url(r'^docs/', include('documentos.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^/slp2015/getNode/$', getNode, name="getNode")
    url('^', include('django.contrib.auth.urls')),
]

SolarBeamApp/Ciudades/models.py
from __future__ import unicode_literals

from django.db import models

class Inversore(models.Model):
    Marca = models.CharField(max_length=30)
    Modelo = models.CharField(max_length=15)
    def __unicode__(self):
        return self.Modelo
    MinPow = models.IntegerField()
    MaxPow = models.IntegerField()
    MaxPowAC = models.IntegerField()
    MPPL = models.IntegerField()
    MPPM = models.IntegerField()
    MinV = models.IntegerField()
    MaxDC = models.FloatField()
    MEfc240 = models.FloatField()
    MEfc208 = models.FloatField()
    A240 = models.FloatField()
    A208 = models.FloatField()
    MA240 = models.FloatField()
    MA208 = models.FloatField()
    Tipo_opciones = (
        ('MI', 'Microinversor'),
        ('IC', 'Inversor Central'),
    )
    Tipo = models.CharField(max_length=2,
                                    choices=Tipo_opciones,
                                    default='IC')



class Panele(models.Model):
    Marca = models.CharField(max_length=30)
    Modelo = models.CharField(max_length=15)
    def __unicode__(self):
        return self.Modelo
    Wp = models.IntegerField()
    Largo = models.IntegerField()
    Ancho = models.IntegerField()
    Peso = models.FloatField()
    Voc = models.FloatField()
    Vmpp = models.FloatField()
    Isc = models.FloatField()
    Impp = models.FloatField()
    PTC = models.FloatField()

class Ciudade(models.Model):
    Nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.Nombre

    Estados_Opciones = (
        ('AG', 'Aguascalientes'),
        ('BC', 'Baja California'),
        ('BS', 'Baja California Sur'),
        ('Ca', 'Campeche'),
        ('Cp', 'Chiapas'),
        ('Ch', 'Chihuahua'),
        ('Cu', 'Coahuila'),
        ('Co', 'Colima'),
        ('DF', 'Distrito Federal'),
        ('Du', 'Durango'),
        ('EM', 'Estado de Mexico'),
        ('Gt', 'Guanajuato'),
        ('Gr', 'Guerrero'),
        ('Hd', 'Hidalgo'),
        ('Ja', 'Jalisco'),
        ('Mi', 'Michoacan'),
        ('Mo', 'Morelos'),
        ('Na', 'Nayarit'),
        ('NL', 'Nuevo Leon'),
        ('Oa', 'Oaxaca'),
        ('Pu', 'Puebla'),
        ('Qt', 'Queretaro'),
        ('QR', 'Quintana Roo'),
        ('SL', 'San Luis Potosi'),
        ('Si', 'Sinaloa'),
        ('So', 'Sonora'),
        ('Ta', 'Tabasco'),
        ('Tm', 'Tamaulipas'),
        ('Tl', 'Tlaxcala'),
        ('Ve', 'Veracruz'),
        ('Yu', 'Yucatan'),
        ('Za', 'Zacatecas'),
    )
    Estados = models.CharField(max_length=2,
                                      choices=Estados_Opciones,
                                      default='AG')
    Latitud = models.FloatField()
    HSP_Ene = models.FloatField()
    HSP_Feb = models.FloatField()
    HSP_Mar = models.FloatField()
    HSP_Abr = models.FloatField()
    HSP_May = models.FloatField()
    HSP_Jun = models.FloatField()
    HSP_Jul = models.FloatField()
    HSP_Ago = models.FloatField()
    HSP_Sep = models.FloatField()
    HSP_Oct = models.FloatField()
    HSP_Nov = models.FloatField()
    HSP_Dic = models.FloatField()
    Temp_Ene = models.FloatField()
    Temp_Feb = models.FloatField()
    Temp_Mar = models.FloatField()
    Temp_Abr = models.FloatField()
    Temp_May = models.FloatField()
    Temp_Jun = models.FloatField()
    Temp_Jul = models.FloatField()
    Temp_Ago = models.FloatField()
    Temp_Sep = models.FloatField()
    Temp_Oct = models.FloatField()
    Temp_Nov = models.FloatField()
    Temp_Dic = models.FloatField()

# Create your models here.

SolarBeamApp/Ciudades/views.py
from django.shortcuts import get_object_or_404, render
from Ciudades.models import Ciudade, Panele, Inversore
from tarifas.models import Meses
import principal,  inicial, inversor, final, graffinal2
from django.utils import timezone

def home(request):

    ciudades = Ciudade.objects.order_by('Estados')
    panel = Panele.objects.all()
    inver = Inversore.objects.all()
    context = {'ciudades': ciudades, 'panel': panel, 'inver': inver}
    return render(request, 'Ciudades/pruebas4.html',context)

def Solarbeam2(request):
    ciudades = Ciudade.objects.order_by('Estados')
    panel = Panele.objects.all()
    inver = Inversore.objects.all()
    context = {'ciudades': ciudades, 'panel': panel, 'inver': inver}
    return render(request, 'Ciudades/SB2index.html',context)

def resultados(request):
    ciudades = Ciudade.objects.order_by('Estados')
    Ciud = get_object_or_404(Ciudade, pk=request.POST['Ciudad'])
    panel = Panele.objects.get(pk = request.POST['Panel'])
    inver = Inversore.objects.get(pk = request.POST['Inversor'])
    per = int(request.POST['ener'])
    tipo = int(request.POST['tipo'])
    kwhanor = float(request.POST['demanda'])
    cab = float(request.POST['cable'])
    meses = Meses.objects.all()
    paneles = Panele.objects.all()
    inversores = Inversore.objects.all()
    kwhan = inicial.main(kwhanor, per)
    kwp, prom, incl, PerT, npan, valinc, hspmensual, kwhan1 = principal.main(Ciud, kwhan, cab, panel, tipo, meses, inver)
    ninver, conex = inversor.main(npan, panel, kwp, inver)
    tempmen, kwh, kwf, hsp, efsist, kwdia, ahorroaino, ahorrodosaino, arb1, arb2, kwhtot = final.main(PerT, kwp, valinc, inver, cab, hspmensual, npan, panel)
    graffinal2.main(kwh)
    hora = timezone.now()
    mes2 = zip(meses, tempmen, kwh)
    context = { 'arb1': arb1,'arb2': arb2,'ahorrodosaino':ahorrodosaino,'ahorroaino':ahorroaino,'kwdia':kwdia, 'efsist':efsist, 'hora':hora,'kwf':kwf,'per': per, 'kwhanor':kwhanor, 'ciudades': ciudades, 'hsp':hsp, 'kwh':kwh, 'Ciud': Ciud, 'kwhan': kwhtot, 'kwp':kwp, 'prom': prom, 'incl': incl, 'mes2':mes2, 'npan':npan, 'panel':panel, 'conex':conex, 'tipo':tipo, 'paneles': paneles, 'inversores': inversores, 'ninver': ninver, 'inver' : inver}
    return render(request, 'Ciudades/pruebas3.html', context)

def resumen(request):
    ciudades = Ciudade.objects.order_by('Estados')
    Ciud = get_object_or_404(Ciudade, pk=request.POST['Ciudad'])
    panel = Panele.objects.get(pk = request.POST['Panel'])
    inver = Inversore.objects.get(pk = request.POST['Inversor'])
    per = int(request.POST['ener'])
    tipo = int(request.POST['tipo'])
    kwhanor = float(request.POST['demanda'])
    cab = float(request.POST['cable'])
    meses = Meses.objects.all()
    paneles = Panele.objects.all()
    inversores = Inversore.objects.all()
    kwhan = inicial.main(kwhanor, per)
    kwp, prom, incl, PerT, npan, valinc, hspmensual, kwhan1 = principal.main(Ciud, kwhan, cab, panel, tipo, meses, inver)
    ninver, conex = inversor.main(npan, panel, kwp, inver)
    tempmen, kwh, kwf, hsp, efsist, kwdia, ahorroaino, ahorrodosaino, arb1, arb2, kwhtot = final.main(PerT, kwp, valinc, inver, cab, hspmensual, npan, panel)
    graffinal2.main(kwh)
    hora = timezone.now()
    mes2 = zip(meses, tempmen, kwh)
    potint = float(ninver*inver.MaxPowAC)/1000
    invpot = float(inver.MaxPowAC)/1000
    context = { 'arb1': arb1,'arb2': arb2,'ahorrodosaino':ahorrodosaino,'ahorroaino':ahorroaino,'kwdia':kwdia, 'efsist':efsist, 'hora':hora,'kwf':kwf,'per': per, 'kwhanor':kwhanor, 'ciudades': ciudades, 'hsp':hsp, 'kwh':kwh, 'Ciud': Ciud, 'kwhan': kwhtot, 'kwp':kwp, 'prom': prom, 'incl': incl, 'mes2':mes2, 'npan':npan, 'panel':panel, 'conex':conex, 'tipo':tipo, 'paneles': paneles, 'inversores': inversores, 'ninver': ninver, 'inver' : inver, 'potint': potint, 'invpot': invpot}
    return render(request, 'Ciudades/resumen2.html', context)

SolarBeamApp/Ciudades/templates/Ciudades/SB2index.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block title %}Solarbeam{% endblock %}
{% block content %}
    <h1 align = center>Solarbeam 2</h1>
        <form name="frmSimulator" id="frmSimulator" onsubmit="return validateForm()" action="resumen/" method="post" >
        {% csrf_token %}
        <div class="row form-group">
            <span class="col-md-2 col-sm-2 col-xs-2 col-lg-2">1.- Quiero generar </span>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="number" step="any" name="demanda" class="form-control" value="{{ kwhanor }}" required/>
            </div>
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">Killowatts-hora (Kwh) &nbsp;en la ciudad de:</span>
            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3">
                <select name="Ciudad">
                    {% for i in ciudades %}
                        <option value="{{i.id}}">{{ i.get_Estados_display }}, {{ i.Nombre }}</option>
                    {% endfor %}
               </select>
            </div>
        </div>
        <div class="row form-group">
            <span class="col-md-4 col-sm-4 col-xs-4 col-lg-4">2.-Quiero generar esta energía cada: </span>
            <div class="col-md-1 col-sm-1 col-xs-1 col-lg-1">
                 <input type="radio" name="ener" value="0" checked/> Mes 
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                 <input type="radio" name="ener" value="1" /> Bimestre 
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                 <input type="radio" name="ener" value="2" /> Semestre 
            </div>
            <div class="col-md-1 col-sm-1 col-xs-1 col-lg-1">
                 <input type="radio" name="ener" value="3" /> Año 
            </div>
        </div>
        <div class="row form-group">
                <span class="col-md-6 col-sm-6 col-xs-6 col-lg-6"> 3.-¿Cuándo quiero que haya mayor generación de energía?: </span>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="radio" name="tipo" value="1" /> Primavera
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="radio" name="tipo" value="2" /> Otoño
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
                <input type="radio" name="tipo" value="0" checked/>Anual
                <input type="hidden" name="cable" value='0.99'>
            </div>
        </div>
        <div class="row form-group">
            <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3"> 4.- Quiero utilizar paneles </span>    
            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3">
                <select name="Panel">     
                    {% for i in panel %}
                        <option value="{{i.id}}">{{ i.get_Marca_display }}{{ i.Marca}}, {{ i.Modelo }}</option>
                    {% endfor %}
                </select>
            </div>
            <span class="col-md-3 col-sm-3 col-xs-3 col-lg-3"> con inversores </span>    
            <div class="col-md-3 col-sm-3 col-xs-3 col-lg-3">
                <select name="Inversor">
                    {% for i in inver %}
                        <option value="{{i.id}}">{{ i.get_Marca_display }}{{ i.Marca}}, {{ i.Modelo }}</option>
                    {% endfor %}
                </select> 
            </div>
        </div>
        <div class="row form-group" align = "center">
           <div class="col-md-2 col-sm-2 col-xs-2 col-lg-2">
            <input type="submit" class="form-control btn-primary" value="Enviar" id="btnSend" />
           </div>
        </div>
        </form>
{% endblock %}

SolarBeamApp/Ciudades/templates/Ciudades/pruebas.html
{% comment %}
{% load google_analytics %}
{% endcomment %}
<!DOCTYPE html>
<html lang="es">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Ciudades/style.css' %}" />
    <title>{% block title %}SolarBeam1.0{% endblock %}</title>
    <meta charset="utf-8"/>
    <meta description="Solar Beam es una aplicación web para el dimensionado de campos solares fotovoltaicos en México"/>
    <link rel="shortcut icon" href="{% static 'imagenes/Logocasifinal.png' %}" />
  {% comment %}  {% google_analytics %} {% endcomment %}
</head>

<body>
    <section id="cabecera">
        <a href="/">
        <header>
        <div style="
            margin-top:1em;
            border-radius: 5px;
            -moz-border-radius: 5px;
            -khtml-border-radius: 5px;
            -webkit-border-radius: 5px;
            width: 200px;
            height: 220px;
            background: url('{% static 'imagenes/logo.png' %}');
            background-size: 200px auto;
            background-repeat: no-repeat;"/>
        </div>
        </header>
        </a>
        <aside>
            {% block sidebar %}

            {% endblock %}
        </aside>



	</section>
	<section id="contenido">
	    {% block content %}

        {% endblock %}
	</section>

    <footer>
        {% block footer %}

        {% endblock %}

    </footer>
</body>
</html>

SolarBeamApp/Ciudades/templates/Ciudades/pruebas3.html
{% extends "Ciudades/pruebas.html" %}
{% load staticfiles %}
{% load humanize %}
{% block title %}Reporte de dimensionamiento{% endblock %}
{% block sidebar %}

    <p>
        <form name = 'entr' onsubmit="return validateForm()" action="/Solarbeam1.0/reporte/" method="post" >
        {% csrf_token %}
        1.-Quiero generar <input type="number" step="any" name="demanda" style="width: 6em" value="{{ kwhanor }}" required/> Killowatts-hora (Kwh) &nbsp;en la ciudad de:&nbsp;<select name="Ciudad">
        {% for i in ciudades %}
            <option value="{{i.id}}">{{ i.get_Estados_display }}, {{ i.Nombre }}</option>
        {% endfor %}
        </select><br><br>
        2.-Quiero generar esta energía cada:
        {% if per == 0 %}
        <input type="radio" name="ener" value="0" checked/> Mes
        <input type="radio" name="ener" value="1" /> Bimestre
        <input type="radio" name="ener" value="2" /> Semestre
        <input type="radio" name="ener" value="3" /> Año<br><br>
        {% elif per == 1 %}
        <input type="radio" name="ener" value="0" /> Mes
        <input type="radio" name="ener" value="1" checked/> Bimestre
        <input type="radio" name="ener" value="2" /> Semestre
        <input type="radio" name="ener" value="3" /> Año<br><br>
        {% elif per == 2 %}
        <input type="radio" name="ener" value="0" /> Mes
        <input type="radio" name="ener" value="1" /> Bimestre
        <input type="radio" name="ener" value="2" checked/> Semestre
        <input type="radio" name="ener" value="3" /> Año<br><br>
        {% else %}
        <input type="radio" name="ener" value="0" /> Mes
        <input type="radio" name="ener" value="1" /> Bimestre
        <input type="radio" name="ener" value="2" /> Semestre
        <input type="radio" name="ener" value="3" checked/> Año<br><br>
        {% endif %}

        3.-¿Cuándo quiero que haya mayor generación de energía?:&nbsp;
        {% if tipo == 0 %}
        <input type="radio" name="tipo" value="1" /> Primavera
        <input type="radio" name="tipo" value="2" /> Otoño
        <input type="radio" name="tipo" value="0" checked/>Anual
        <input type="hidden" name="cable" value='0.99'><br><br>
        {% elif tipo == 1 %}
        <input type="radio" name="tipo" value="1" checked/> Primavera
        <input type="radio" name="tipo" value="2" /> Otoño
        <input type="radio" name="tipo" value="0" />Anual
        <input type="hidden" name="cable" value='0.99'><br><br>
        {% else %}
        <input type="radio" name="tipo" value="1" /> Primavera
        <input type="radio" name="tipo" value="2" checked/> Otoño
        <input type="radio" name="tipo" value="0" />Anual
        <input type="hidden" name="cable" value='0.99'><br><br>
        {% endif %}

        4.- Quiero utilizar paneles    
        <select name="Panel">     
        {% for i in paneles %}
            <option value="{{i.id}}">{{ i.get_Marca_display }}{{ i.Marca}}, {{ i.Modelo }}</option>
        {% endfor %}
        </select>
        con un inversores 
        <select name="Inversor">
        {% for i in inversores %}
            <option value="{{i.id}}">{{ i.get_Marca_display }}{{ i.Marca}}, {{ i.Modelo }}</option>
        {% endfor %}
        </select><br><br>
        <div class="centrar"><input type="submit" value="Enviar" id="btn_s" /></div>
        </form>
    {% endblock %}
{% block content %}
    <section id="contenido1">
    <section id="princpal">
    <p style="text-align:left;">
        Solarbeam 1.0
        <span style="float:right;">{{ hora.day }}/{{ hora.month }}/{{ hora.year }} a las {{ hora.hour }}:{{ hora.minute }}</span>
    </p>
            </section>
            <section id="pagina2">
                <h1>Reporte de dimensionamiento fotovoltaico interconectado </h1>

    <table>
        <tr><td style="padding:25px;"><img src="{% static 'imagenes/Header_03.png' %}" style="max-width:100%;height:auto;"></td><td style="padding:25px;"><img src="{% static 'imagenes/Header_02.png' %}" style="max-width:100%;height:auto;"></td></tr>
    </table>
                <section id="pag2x1">
                <img src="{% static 'imagenes/grafica1.jpg' %}" style="max-width:100%;height:auto; border:1px solid #;
-webkit-border-radius: 3px;
-moz-border-radius: 3px;
border-radius: 3px;">
                </section>
                <section id="pag2x2">
                <table id="tabla1">
                    <tr>
                            <th rowspan="2"><img src="{% static 'imagenes/Icono_02.png' %}" style="max-width:100%;height:auto;"></th>
                            <td style="padding-left:15px;">Estado: {{ Ciud.get_Estados_display }}</td>
                    </tr>
                    <tr>    <td style="padding-left:15px;">Ciudad: {{ Ciud.Nombre }}</td></tr>
                    <tr>
                    <th rowspan="2"><img src="{% static 'imagenes/Icono_05.png' %}" style="max-width:100%;height:auto;"></th>
                            <td style="padding-left:15px;">{{ ahorroaino | floatformat:-2 |intcomma}}$ pesos ahorrados el primer año*</td>
                    </tr>
                    <tr>    <td style="padding-left:15px;">{{ ahorrodosaino | floatformat:-2 |intcomma}}$ pesos ahorrados en los 25 años de garantía del sistema**</td></tr>
                    <tr>
                    <th rowspan="2"><img src="{% static 'imagenes/Icono_03.png' %}" style="max-width:100%;height:auto;"></th>
                        <td style="padding-left:15px;">{{ kwdia | floatformat:-2 |intcomma}} kWh producidos diariamente </td>
                    </tr>
                    <tr>    <td style="padding-left:15px;">{{kwhan | floatformat:-2 |intcomma}} kWh producidos anualmente</td></tr>
                    <tr>
                    <th rowspan="2"><img src="{% static 'imagenes/Icono_06.png' %}" style="max-width:100%;height:auto;"></th>
                      <td style="padding-left:15px;">Potencia del sistema de generación: {{ kwf|floatformat:-2 |intcomma }} kWp </td>
                    </tr>
                    <tr>  <td style="padding-left:15px;">Número de paneles: {{npan|floatformat}} de {{panel.Wp}} Wp</td>   </tr>
                    <tr>
                    <th rowspan="2"><img src="{% static 'imagenes/Icono_04.png' %}" style="max-width:100%;height:auto;"></th>
                     <td style="padding-left:15px;">Eficiencia de los paneles: 15.37%</td>
                    </tr>
                    <tr>    <td style="padding-left:15px;">Eficiencia del sistema: {{ efsist | floatformat:-2 }}%</td>
                    </tr>
                     <tr>
                            <th rowspan="2"><img src="{% static 'imagenes/icono_01.png' %}" style="max-width:100%;height:auto;"></th>
                            <td style="padding-left:15px;">Se tendrá la mayor producción en{% if tipo == 0 %} todo el año{% elif tipo == 1 %} la primavera {% else %} el otoño{% endif %}</td>
                    </tr>
                    <tr>    <td style="padding-left:15px;">Los paneles deberán tener una inclinación de {{ incl| floatformat:0 }} grados</td></tr>
                     <tr>
                            <th rowspan="2"><img src="{% static 'imagenes/co2_02.png' %}" style="max-width:100%;height:auto;"></th>
                            <td style="padding-left:15px;">Se evitará la emisión de  {{ arb1| floatformat:2 }} toneladas de CO2***</td>
                    </tr>
                    <tr>    <td style="padding-left:15px;">Equivalente a plantar {{ arb2| floatformat:0 }} árboles****</td></tr>
                    <tr>
                            <th rowspan="2"><img src="{% static 'imagenes/co2_02.png' %}" style="max-width:100%;height:auto;"></th>
                            <td style="padding-left:15px;">Se necesitarán {{ ninver| floatformat:0 }} inversores</td></tr>
                    <tr>    <td style="padding-left:15px;">Se utilizaran inversores {{ inver.Marca }} {{ inver.Modelo}} de {{ inver.MaxPowAC}} Watts</td></tr>
                    


                </table>

                </section>

            </section>

            <section id="pagina3">
            {% for i in conex %}
                <h4>Aspectos generales de la instalación</h4>
                <table align="center" id="panel">
                    <tr>
                        <td id ="estilo1" ></td>
                        <td id ="estilo1" ></></td>
                        <td id ="estilo1" ></td>
                        <td id ="estilo1" ></></td>
                        <td id ="estilo1" ></td>
                    </tr>

                    <tr>
                        <td >Potencia del campo solar: {{ kwf|floatformat:-2 }} kWp</td>
                        <td >Latitud: {{ incl| floatformat:0 }} grados</td>
                        <td ># de paneles: {{npan|floatformat}} de {{panel.Wp}} Wp</td>
                        <td ># de inversores: {{ ninver }} inversor/es de {{inver.MaxPowAC}}kW</td>
                        <td ># de paneles conectados en serie: {{ i.0 }}</td>
                    <tr>
                        <td id ="estilo2" ></td>
                        <td id ="estilo2" ></></td>
                        <td id ="estilo2" ></td>
                        <td id ="estilo2" ></></td>
                        <td id ="estilo2" ></td>
                    </tr>
                    <tr>
                        <td id ="estilo1" ></td>
                        <td id ="estilo1" ></></td>
                        <td id ="estilo1" ></td>
                        <td id ="estilo1" ></></td>
                        <td id ="estilo1" ></td>
                    </tr>

                        <td ># de ramas conectadas en paralelo: {{ i.1 }}</td>
                        <td >Voltaje en circuito abierto: {{ i.3 }} Voltios</td>
                        <td >Amperaje en circuito abierto: {{ i.5 }} Amperes</td>
                        <td >Voltaje de funcionamiento: {{ i.4 }} Voltios</td>
                        <td >Amperaje de funcionamiento: {{ i.6 }} Amperes</td>

                    </tr>
                    <tr>
                        <td id ="estilo2" ></td>
                        <td id ="estilo2" ></></td>
                        <td id ="estilo2" ></td>
                        <td id ="estilo2" ></></td>
                        <td id ="estilo2" ></td>
                    </tr>

                </table>
            {% endfor %}
            </section>

    </section>
{% endblock %}
{% block footer %}
<table>
                    <tr>
                        <td style="padding:0.5em;">*Ahorro con un costo de $3.80 el kWh</td>
                        <td style="padding:0.5em;">**Ahorro a 25 años con un costo de $3.80 el kWh</td>
                        <td style="padding:0.5em;">***Se tomo una emisión de 0.65kg por kWh producido</td>
                        <td style="padding:0.5em;">****Cantidad de árboles con una taza de absorción de 10kg anuales de CO2</td>

                    </tr>
                </table>
{% endblock %}